# SETUP
baseurl = "https://storyof.place"
publishdir = "public"
canonifyUrls = "true"
disableKinds = ["RSS","taxonomy","taxonomyTerm","sitemap"]

[params]
    author = "ttntm"
    DateForm = "02.01.2006"
    showReadTime = 1
    title = "Hugo+Leaflet Store Locator JT"
    description = "A Leaflet based store locator rendered as a static site by hugo."